import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'cs' | 'en' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  cs: {
    // Header
    'header.menu': 'Jídelní lístek',
    'header.gallery': 'Galerie',
    'header.call': 'Zavolat',
    'header.reserve': 'Rezervovat stůl',
    'header.trust': 'hodnocení na Google (64+ recenzí)',
    'header.experience': '20+ let zkušeností',
    
    // Navigation
    'nav.home': 'Domů',
    'nav.about': 'O nás',
    'nav.menu': 'Menu',
    'nav.daily': 'Týdenní menu',
    'nav.reserve': 'Rezervace',
    'nav.contact': 'Kontakt',
    
    // Hero
    'hero.subtitle': 'Autentická italská kuchyně v srdci Prahy',
    'hero.description': 'Tradiční neapolská pizza z pece Morello Forni • Domácí čerstvá pasta • Autentická italská pohostinnost',
    'hero.viewMenu': 'Prohlédnout menu',
    'hero.years': '20+ let zkušeností',
    'hero.fresh': 'Denně čerstvé suroviny',
    'hero.reserve': 'Rezervovat stůl',
    'hero.call': 'Zavolat',
    'hero.urgency': '⚡ Omezená kapacita - Rezervujte si stůl včas',
    'hero.address': 'Adresa',
    'hero.location': 'Korunní 48, Praha 2',
    'hero.hours': 'Otevírací doba',
    'hero.schedule': 'Po-Ne: 11:00 - 23:00',
    'hero.chef': 'Majitel & Šéfkuchař',
    'hero.chefName': 'Antonín Sahulka',
    
    // Locale for date picker
    'locale': 'cs',
    
    // About
    'about.title': 'Zažijte chuť\npravé Itálie',
    'about.p1': 'V Altro Da Tony spojujeme lásku k italské kuchyni a kvalitním surovinám. Náš šéfkuchař má více než 20 let zkušeností s italskou gastronomií.',
    'about.p2': 'Každé jídlo připravujeme s láskou a péčí, protože věříme, že dobrá kuchyně spojuje lidi.',
    'about.stat1': 'Let zkušeností',
    'about.stat2': 'Čerstvé suroviny',
    'about.stat3': 'Spokojených hostů',
    'about.cta': 'Prohlédnout menu',
    'about.chefLabel': 'Majitel & Šéfkuchař',
    'about.chefYears': '20+ let zkušeností',
    'about.ownerTitle': 'Příběh majitele',
    'about.ownerP1': 'Altro Da Tony není jen restaurace – je to splněný sen. Po více než dvaceti letech zkušeností v italských restauracích jsem se rozhodl otevřít své vlastní místo, kde mohu sdílet svou vášeň pro autentickou italskou kuchyni a tradiční neapolskou pizzu.',
    'about.ownerP2': 'Dnes kombinuji tradiční italské techniky s čerstvými lokálními surovinami, abych vytvořil nezapomenutelný gastronomický zážitek.',
    'about.ownerP3': 'V Altro Da Tony nejde jen o jídlo – jde o atmosféru, rodinu a sdílení radosti u stolu. Každý host je pro nás jako přítel, kterého vítáme doma.',
    'about.ownerQuote': 'Vaření není jen o krmení lidí – je to o vytváření vzpomínek, emocí a spojování rodin u stolu.',
    'about.ownerQuoteShort': 'Vaření je o emocích a spojování lidí.',
    'contact.days': 'Pondělí - Neděle',
    'reservation.groups': 'Pro skupiny 10+ osob volejte',
    'reviews.example': 'Nejlepší italská restaurace na Vinohradech. Skvělá atmosféra a ještě lepší jídlo.',
    
    // Gallery
    'gallery.title': 'Naše speciality',
    'gallery.subtitle': 'Každé jídlo připravujeme s láskou k detailu a respektem k italským tradicím',
    'gallery.carbonara': 'Pasta Carbonara',
    'gallery.pizza': 'Pizza Margherita',
    'gallery.tiramisu': 'Tiramisu',
    'gallery.burrata': 'Burrata Fresca',
    'gallery.wine': 'Vína z Itálie',
    'gallery.oven': 'Morello Forni Pec',
    'gallery.cat.pasta': 'Pasta',
    'gallery.cat.pizza': 'Pizza',
    'gallery.cat.dolci': 'Dolci',
    'gallery.cat.antipasti': 'Antipasti',
    'gallery.cat.wine': 'Wine',
    'gallery.cat.restaurant': 'Restaurant',
    'gallery.question': 'Těšíte se na autentickou italskou kuchyň?',
    'gallery.cta': 'Rezervovat stůl',
    
    // Gallery Items
    'gallery.item1.title': 'Pizza Napoletana',
    'gallery.item1.category': 'Z Pece',
    'gallery.item2.title': 'Interiér Restaurace',
    'gallery.item2.category': 'Zákulisí',
    'gallery.item3.title': 'Altro Da Tony',
    'gallery.item3.category': 'Autentická Itálie',
    'gallery.item4.title': 'Italské Espresso',
    'gallery.item4.category': 'Prémiová Káva',
    'gallery.item5.title': 'Dokonalá Pasta',
    'gallery.item5.category': 'Denně Čerstvá',
    'gallery.item6.title': 'Čerstvé Suroviny',
    'gallery.item6.category': 'Čistá Kvalita',
    
    // Featured Dish
    'featured.badge': '',
    'featured.title': 'Proč naše pizza chutná?',
    'featured.description': 'Každá pizza, kterou servírujeme, je výsledkem let zkoušení a ladění. Těsto necháváme zrát 48 hodin – díky tomu je lehké a skvěle stravitelné. Suroviny nelžou, a proto používáme jen San Marzano rajčata a čerstvou mozzarellu. Pečeme v rotační peci Morello Forni, která zaručuje vždy perfektní výsledek. Žádná kouzla, jen poctivé řemeslo.',
    'featured.fact': 'Zajímavost: Rajčata San Marzano, která používáme, rostou na sopečné půdě pod Vesuvem. Právě minerály z lávy jim dodávají tu specifickou, sladkou chuť, kterou nelze ničím nahradit.',
    'featured.chefChoice': '',
    
    // Menu
    'menu.title': 'Stálá nabídka',
    'menu.subtitle': 'Čerstvé suroviny, tradiční recepty a láska k italské kuchyni',
    'menu.daily': 'Týdenní menu',
    'menu.antipasti': 'Předkrmy',
    'menu.insalate': 'Saláty',
    'menu.pasta': 'Pasta',
    'menu.pizza': 'Pizza',
    'menu.secondi': 'Hlavní jídla',
    'menu.dolci': 'Dezerty',
    'menu.primi': 'Primi Piatti',
    'menu.badge.popular': 'Nejoblíbenější',
    'menu.badge.chef': 'Doporučení šéfkuchaře',
    'menu.badge.vegetarian': 'Vegetariánské',
    'menu.allergens': 'Máte alergie nebo dietní omezení?',
    'menu.allergensText': 'Neváhejte se zeptat našeho personálu. Rádi Vám přizpůsobíme menu.',
    'menu.cta': 'Rezervovat stůl',
    
    // Menu Categories - Drinks
    'menu.drinks': 'Nápoje',
    'menu.wines': 'Vína',
    'menu.wines_white': 'Bílá vína',
    'menu.wines_red': 'Červená vína',
    'menu.wines_rose': 'Růžová vína',
    'menu.wines_sparkling': 'Prosecco & Šampaňské',
    'menu.beers': 'Piva',
    'menu.aperitivi': 'Aperitivy',
    'menu.cocktails': 'Koktejly',
    'menu.digestivi': 'Digestivy',
    'menu.grappa': 'Grappa',
    'menu.nonalcoholic': 'Nealkoholické nápoje',
    'menu.coffee': 'Káva',
    'menu.food': 'Jídla',
    
    // Wine descriptions
    'menu.wine.bottle': 'láhev',
    'menu.wine.glass': 'sklenka',
    
    // Reviews
    'reviews.title': 'Co říkají naši hosté',
    'reviews.based': 'Na základě',
    'reviews.reviews': '+ recenzí',
    'reviews.google': 'Google Reviews',
    'reviews.all': 'Zobrazit všechny recenze na Google',
    'reviews.write': 'Napište recenzi',
    'reviews.join': 'Přidejte se k našim spokojeným hostům',
    'reviews.joinText': 'Rezervujte si stůl a zažijte autentickou italskou pohostinnost',
    'reviews.cta': 'Rezervovat stůl',
    
    // Reservation
    'reservation.title': 'Rezervujte si stůl',
    'reservation.subtitle': 'Zajistěte si místo v naší restauraci a užijte si autentickou italskou kuchyni',
    'reservation.urgency': 'Omezená kapacita - Rezervujte včas!',
    'reservation.name': 'Jméno a příjmení',
    'reservation.email': 'Email',
    'reservation.phone': 'Telefon',
    'reservation.guests': 'Počet hostů',
    'reservation.date': 'Datum',
    'reservation.datePlaceholder': 'Vyberte datum',
    'reservation.time': 'Čas',
    'reservation.timePlaceholder': 'Vyberte čas',
    'reservation.message': 'Poznámka',
    'reservation.messagePlaceholder': 'Speciální požadavky, alergie, oslava...',
    'reservation.occasion': 'Speciální příležitost?',
    'reservation.occasionPlaceholder': 'Vyberte příležitost',
    'reservation.occasionBusiness': 'Pracovní',
    'reservation.occasionRomance': 'Romantika',
    'reservation.occasionFriends': 'Přátelé',
    'reservation.occasionFamily': 'Rodina',
    'reservation.occasionCelebration': 'Oslava',
    'reservation.occasionOther': 'Jiné',
    'reservation.submit': 'Potvrdit rezervaci',
    'reservation.trust1': 'Potvrzení do 1 hodiny',
    'reservation.trust2': 'Bez poplatků',
    'reservation.trust3': 'Snadná změna rezervace',
    'reservation.alternative': 'Preferujete osobní kontakt?',
    'reservation.open': 'Otevřeno Po-Ne: 11:00 - 23:00',
    'reservation.success': 'Děkujeme za rezervaci! Vaše rezervace byla odeslána ke zpracování.',
    'reservation.person': 'osoba',
    'reservation.persons2': 'osoby',
    'reservation.persons5': 'osob',
    'reservation.sending': 'Odesílám...',
    'reservation.summary': 'Souhrn rezervace',
    'reservation.continue': 'Pokračovat',
    'reservation.back': 'Zpět',
    'reservation.fillAll': 'je povinné pole',
    'reservation.error': 'Něco se pokazilo. Zkuste to prosím znovu nebo nás kontaktujte telefonicky.',
    
    // Contact
    'contact.title': 'Kontakt',
    'contact.address': 'Adresa',
    'contact.addressLine1': 'Korunní 48',
    'contact.addressLine2': '120 00 Praha 2 - Vinohrady',
    'contact.phone': 'Telefon',
    'contact.email': 'Email',
    'contact.hours': 'Otevírací doba',
    'contact.schedule': 'Pondělí - Neděle: 11:00 - 23:00',
    
    // Footer
    'footer.about': 'Autentická italská kuchyně v srdci Prahy. Rodinný podnik s tradicí a láskou k italské gastronomii.',
    'footer.menu': 'Menu',
    'footer.contact': 'Kontakt',
    'footer.hours': 'Otevírací doba:',
    'footer.schedule': 'Po-Ne: 11:00 - 23:00',
    'footer.kitchenUntil': 'Kuchyně vaří do 22:00',
    'footer.copyright': 'Altro da Tony. Všechna práva vyhrazena.',
    'footer.made': 'Vytvořeno s',
    'footer.madeFor': 'pro milovníky italské kuchyně',
    
    // Holiday Hours
    'holidayHours.title': 'Otevírací doba během svátků',
    'holidayHours.subtitle': 'Přejeme krásné svátky a těšíme se na Vaši návštěvu',
    'holidayHours.dec24': 'Štědrý den (24.12.)',
    'holidayHours.dec25': '1. svátek vánoční (25.12.)',
    'holidayHours.dec26': '2. svátek vánoční (26.12.)',
    'holidayHours.dec27': '27. prosince',
    'holidayHours.dec28': '28. prosince',
    'holidayHours.dec29': '29. prosince',
    'holidayHours.dec30': '30. prosince',
    'holidayHours.dec31': 'Silvestr (31.12.)',
    'holidayHours.jan1': 'Nový rok (1.1.)',
    'holidayHours.closed': 'Zavřeno',
    'holidayHours.welcomeMessage': 'Těšíme se na Vaši návštěvu během svátků!',
    'holidayHours.teamSignature': 'Tým Altro Da Tony',
    
    // Daily Menu
    'daily.title': 'Speciality tohoto týdne',
    'daily.servingTime': 'Servito 11:00 - 15:00',
    'daily.disclaimer': 'Il menu può variare a seconda della disponibilità di ingredienti freschi',
    'daily.soup': 'Zuppa',
    'daily.starter': 'Antipasto',
    'daily.main': 'Primo',
    'daily.dessert': 'Dolce',
    'daily.soups': 'Zuppe',
    'daily.mains': 'Primi',
    'daily.desserts': 'Dolci',
    
    // Admin Panel
    'admin.dailyMenu': 'Menu Settimanale',
    'admin.mainMenu': 'Gestione Menu Principale',
    'admin.reservations': 'Prenotazioni',
    'admin.monday': 'Lunedì',
    'admin.tuesday': 'Martedì',
    'admin.wednesday': 'Mercoledì',
    'admin.thursday': 'Giovedì',
    'admin.friday': 'Venerdì',
    'admin.saturday': 'Sabato',
    'admin.sunday': 'Domenica',
    'admin.add': 'Aggiungi Elemento',
    'admin.save': 'Salva Tutto',
    'admin.delete': 'Elimina',
    'admin.edit': 'Modifica',
    'admin.cancel': 'Annulla',
    'admin.name': 'Nome',
    'admin.description': 'Descrizione',
    'admin.price': 'Prezzo',
    'admin.category': 'Categoria',
    'admin.image': 'URL Immagine',
    'admin.reset': 'Carica Menu Predefinito',
    'admin.visible': 'visibili',
    'admin.hidden': 'nascosti',
    'admin.hide': 'Nascondi dal Sito Web',
    'admin.show': 'Mostra sul Sito Web',
    
    // Menu Items - Antipasti
    'item.bruschetta.name': 'Bruschetta al Pomodoro',
    'item.bruschetta.desc': 'Grilovaný chléb s rajčaty, bazalkou a olivovým olejem',
    'item.carpaccio.name': 'Carpaccio di Manzo',
    'item.carpaccio.desc': 'Tenké plátky hovězího masa s rukolou a parmazánem',
    'item.prosciutto_melone.name': 'Prosciutto e Melone',
    'item.prosciutto_melone.desc': 'Parmská šunka s čerstvým melounem',
    'item.caprese.name': 'Caprese',
    'item.caprese.desc': 'Mozzarella, rajčata, bazalka, olivový olej',
    'item.burrata.name': 'Burrata con Pomodorini',
    'item.burrata.desc': 'Burrata s cherry rajčátky a bazalkou',
    
    // Menu Items - Primi (Pasta)
    'item.carbonara.name': 'Spaghetti Carbonara',
    'item.carbonara.desc': 'Spaghetti s pancettou, vejcem a parmazánem',
    'item.aglio_olio.name': 'Spaghetti Aglio e Olio',
    'item.aglio_olio.desc': 'Spaghetti s česnekem, olivovým olejem a peperoncinem',
    'item.arrabbiata.name': 'Penne all\'Arrabbiata',
    'item.arrabbiata.desc': 'Penne s pikantní rajčatovou omáčkou',
    'item.tagliatelle_ragu.name': 'Tagliatelle al Ragù',
    'item.tagliatelle_ragu.desc': 'Domácí tagliatelle s masovou omáčkou',
    'item.risotto_funghi.name': 'Risotto ai Funghi',
    'item.risotto_funghi.desc': 'Krémové rizoto s lesními houbami',
    'item.gnocchi_gorgonzola.name': 'Gnocchi al Gorgonzola',
    'item.gnocchi_gorgonzola.desc': 'Domácí gnocchi se sýrovou omáčkou',
    
    // Menu Items - Pizza
    'item.margherita.name': 'Pizza Margherita',
    'item.margherita.desc': 'Rajčatová omáčka, mozzarella, bazalka',
    'item.quattro_formaggi.name': 'Pizza Quattro Formaggi',
    'item.quattro_formaggi.desc': 'Čtyři druhy sýrů',
    'item.prosciutto_funghi.name': 'Pizza Prosciutto e Funghi',
    'item.prosciutto_funghi.desc': 'Šunka a žampiony',
    'item.diavola.name': 'Pizza Diavola',
    'item.diavola.desc': 'Pikantní salám, peperoncino',
    
    // Menu Items - Secondi
    'item.scaloppine.name': 'Scaloppine al Limone',
    'item.scaloppine.desc': 'Telecí plátky v citronové omáčce',
    'item.pollo_milanese.name': 'Pollo alla Milanese',
    'item.pollo_milanese.desc': 'Smažený kuřecí řízek',
    'item.ossobuco.name': 'Ossobuco',
    'item.ossobuco.desc': 'Hovězí koleno na víně s gremolata',
    'item.branzino.name': 'Branzino al Forno',
    'item.branzino.desc': 'Pečený mořský vlk s bylinkami',
    
    // Menu Items - Dolci
    'item.tiramisu.name': 'Tiramisù',
    'item.tiramisu.desc': 'Klasický italský dezert s mascarpone a kávou',
    'item.panna_cotta.name': 'Panna Cotta',
    'item.panna_cotta.desc': 'Smetanový dezert s lesním ovocem',
    'item.cannoli.name': 'Cannoli Siciliani',
    'item.cannoli.desc': 'Tradiční sicilské trubičky s ricottou',
    'item.gelato.name': 'Gelato Artigianale',
    'item.gelato.desc': 'Domácí italská zmrzlina',
  },
  en: {
    // Header
    'header.menu': 'Menu',
    'header.gallery': 'Gallery',
    'header.call': 'Call',
    'header.reserve': 'Book a Table',
    'header.trust': 'rating on Google (64+ reviews)',
    'header.experience': '20+ years of experience',
    
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.menu': 'Menu',
    'nav.daily': 'Weekly Menu',
    'nav.reserve': 'Reservation',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.subtitle': 'Authentic Italian Cuisine in the Heart of Prague',
    'hero.description': 'Traditional Neapolitan pizza from Morello Forni • Homemade fresh pasta • Authentic Italian hospitality',
    'hero.viewMenu': 'View Menu',
    'hero.years': '20+ years of experience',
    'hero.fresh': 'Fresh ingredients daily',
    'hero.reserve': 'Book a Table',
    'hero.call': 'Call',
    'hero.urgency': '⚡ Limited capacity - Book your table early',
    'hero.address': 'Address',
    'hero.location': 'Korunní 48, Prague 2',
    'hero.hours': 'Opening Hours',
    'hero.schedule': 'Mon-Sun: 11:00 AM - 11:00 PM',
    'hero.chef': 'Owner & Head Chef',
    'hero.chefName': 'Antonín Sahulka',
    
    // Locale for date picker
    'locale': 'en',
    
    // About
    'about.title': 'Experience the Taste\nof Real Italy',
    'about.p1': 'At Altro Da Tony, we combine our love for Italian cuisine with quality ingredients. Our head chef has more than 20 years of experience in Italian gastronomy.',
    'about.p2': 'We prepare each dish with love and care, because we believe that good cuisine brings people together.',
    'about.stat1': 'Years of experience',
    'about.stat2': 'Fresh ingredients',
    'about.stat3': 'Satisfied guests',
    'about.cta': 'View Menu',
    'about.chefLabel': 'Owner & Head Chef',
    'about.chefYears': '20+ years of experience',
    'about.ownerTitle': 'Owner\'s Story',
    'about.ownerP1': 'Altro Da Tony is not just a restaurant – it is a fulfilled dream. After more than twenty years of experience in Italian restaurants, I decided to open my own place where I can share my passion for authentic Italian cuisine and traditional Neapolitan pizza.',
    'about.ownerP2': 'Today, I combine traditional Italian techniques with fresh local ingredients to create an unforgettable gastronomic experience.',
    'about.ownerP3': 'At Altro Da Tony, it\'s not just about the food – it\'s about the atmosphere, family, and sharing joy at the table. Every guest is like a friend who we welcome home.',
    'about.ownerQuote': 'Cooking is not just about feeding people – it\'s about creating memories, emotions, and bringing families together at the table.',
    'about.ownerQuoteShort': 'Cooking is about emotions and connecting people.',
    'contact.days': 'Monday - Sunday',
    'reservation.groups': 'For groups of 10+ please call',
    'reviews.example': 'Best Italian restaurant in Vinohrady. Great atmosphere and even better food.',
    
    // Gallery
    'gallery.title': 'Our Specialties',
    'gallery.subtitle': 'Each dish is prepared with attention to detail and respect for Italian traditions',
    'gallery.carbonara': 'Pasta Carbonara',
    'gallery.pizza': 'Pizza Margherita',
    'gallery.tiramisu': 'Tiramisu',
    'gallery.burrata': 'Fresh Burrata',
    'gallery.wine': 'Italian Wines',
    'gallery.oven': 'Morello Forni Oven',
    'gallery.cat.pasta': 'Pasta',
    'gallery.cat.pizza': 'Pizza',
    'gallery.cat.dolci': 'Dolci',
    'gallery.cat.antipasti': 'Antipasti',
    'gallery.cat.wine': 'Wine',
    'gallery.cat.restaurant': 'Restaurant',
    'gallery.question': 'Looking forward to authentic Italian cuisine?',
    'gallery.cta': 'Book a Table',
    
    // Gallery Items
    'gallery.item1.title': 'Pizza Napoletana',
    'gallery.item1.category': 'From Oven',
    'gallery.item2.title': 'Restaurant Interior',
    'gallery.item2.category': 'Backstage',
    'gallery.item3.title': 'Altro Da Tony',
    'gallery.item3.category': 'Authentic Italy',
    'gallery.item4.title': 'Italian Espresso',
    'gallery.item4.category': 'Premium Coffee',
    'gallery.item5.title': 'Perfect Pasta',
    'gallery.item5.category': 'Daily Fresh',
    'gallery.item6.title': 'Fresh Ingredients',
    'gallery.item6.category': 'Clean Quality',
    
    // Featured Dish
    'featured.badge': '',
    'featured.title': 'Why Does Our Pizza Taste So Good?',
    'featured.description': "Every pizza we serve is the result of years of testing and refining. We let the dough mature for 48 hours – making it light and easily digestible. Ingredients don't lie, which is why we only use San Marzano tomatoes and fresh mozzarella. We bake in a Morello Forni rotary oven, guaranteeing a perfect result every time. No magic, just honest craftsmanship.",
    'featured.fact': 'Fun fact: The San Marzano tomatoes we use grow on volcanic soil beneath Mount Vesuvius. It is the minerals from the lava that give them that specific, sweet taste that cannot be replaced.',
    'featured.chefChoice': '',
    
    // Menu
    'menu.title': 'Menu',
    'menu.subtitle': 'Fresh ingredients, traditional recipes and love for Italian cuisine',
    'menu.daily': 'Weekly Menu',
    'menu.antipasti': 'Starters',
    'menu.insalate': 'Salads',
    'menu.pasta': 'Pasta',
    'menu.pizza': 'Pizza',
    'menu.secondi': 'Main Courses',
    'menu.dolci': 'Desserts',
    'menu.primi': 'Primi Piatti',
    'menu.badge.popular': 'Most Popular',
    'menu.badge.chef': "Chef's Recommendation",
    'menu.badge.vegetarian': 'Vegetarian',
    'menu.allergens': 'Do you have allergies or dietary restrictions?',
    'menu.allergensText': "Don't hesitate to ask our staff. We'll be happy to customize the menu for you.",
    'menu.cta': 'Book a Table',
    
    // Menu Categories - Drinks
    'menu.drinks': 'Drinks',
    'menu.wines': 'Wines',
    'menu.wines_white': 'White Wines',
    'menu.wines_red': 'Red Wines',
    'menu.wines_rose': 'Rosé Wines',
    'menu.wines_sparkling': 'Prosecco & Sparkling Wines',
    'menu.beers': 'Beers',
    'menu.aperitivi': 'Aperitifs',
    'menu.cocktails': 'Cocktails',
    'menu.digestivi': 'Digestifs',
    'menu.grappa': 'Grappa',
    'menu.nonalcoholic': 'Non-Alcoholic Drinks',
    'menu.coffee': 'Coffee',
    'menu.food': 'Food',
    
    // Wine descriptions
    'menu.wine.bottle': 'bottle',
    'menu.wine.glass': 'glass',
    
    // Reviews
    'reviews.title': 'What Our Guests Say',
    'reviews.based': 'Based on',
    'reviews.reviews': '+ reviews',
    'reviews.google': 'Google Reviews',
    'reviews.all': 'View all reviews on Google',
    'reviews.write': 'Write a review',
    'reviews.join': 'Join our satisfied guests',
    'reviews.joinText': 'Book a table and experience authentic Italian hospitality',
    'reviews.cta': 'Book a Table',
    
    // Reservation
    'reservation.title': 'Book a Table',
    'reservation.subtitle': 'Reserve your spot in our restaurant and enjoy authentic Italian cuisine',
    'reservation.urgency': 'Limited capacity - Book early!',
    'reservation.name': 'Full Name',
    'reservation.email': 'Email',
    'reservation.phone': 'Phone',
    'reservation.guests': 'Number of Guests',
    'reservation.date': 'Date',
    'reservation.datePlaceholder': 'Select date',
    'reservation.time': 'Time',
    'reservation.timePlaceholder': 'Select time',
    'reservation.message': 'Message',
    'reservation.messagePlaceholder': 'Special requests, allergies, celebration...',
    'reservation.occasion': 'Special Occasion?',
    'reservation.occasionPlaceholder': 'Select occasion',
    'reservation.occasionBusiness': 'Business',
    'reservation.occasionRomance': 'Romantic',
    'reservation.occasionFriends': 'Friends',
    'reservation.occasionFamily': 'Family',
    'reservation.occasionCelebration': 'Celebration',
    'reservation.occasionOther': 'Other',
    'reservation.submit': 'Confirm Reservation',
    'reservation.trust1': 'Confirmation within 1 hour',
    'reservation.trust2': 'No fees',
    'reservation.trust3': 'Easy to change reservation',
    'reservation.alternative': 'Prefer personal contact?',
    'reservation.open': 'Open Mon-Sun: 11:00 AM - 11:00 PM',
    'reservation.success': 'Thank you for your reservation! Your request has been sent for processing.',
    'reservation.person': 'person',
    'reservation.persons2': 'people',
    'reservation.persons5': 'people',
    'reservation.sending': 'Sending...',
    'reservation.summary': 'Reservation Summary',
    'reservation.continue': 'Continue',
    'reservation.back': 'Back',
    'reservation.fillAll': 'is a required field',
    'reservation.error': 'Something went wrong. Please try again or contact us by phone.',
    
    // Contact
    'contact.title': 'Contact',
    'contact.address': 'Address',
    'contact.addressLine1': 'Korunní 48',
    'contact.addressLine2': '120 00 Prague 2 - Vinohrady',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Opening Hours',
    'contact.schedule': 'Monday - Sunday: 11:00 AM - 11:00 PM',
    
    // Footer
    'footer.about': 'Authentic Italian cuisine in the heart of Prague. A family business with tradition and love for Italian gastronomy.',
    'footer.menu': 'Menu',
    'footer.contact': 'Contact',
    'footer.hours': 'Opening Hours:',
    'footer.schedule': 'Mon-Sun: 11:00 AM - 11:00 PM',
    'footer.kitchenUntil': 'Kitchen cooks until 10:00 PM',
    'footer.copyright': 'Altro da Tony. All rights reserved.',
    'footer.made': 'Made with',
    'footer.madeFor': 'for lovers of Italian cuisine',
    
    // Holiday Hours
    'holidayHours.title': 'Opening Hours During Holidays',
    'holidayHours.subtitle': 'Wishing you a beautiful holiday and looking forward to your visit',
    'holidayHours.dec24': 'Christmas Eve (24.12.)',
    'holidayHours.dec25': '1st Christmas Day (25.12.)',
    'holidayHours.dec26': '2nd Christmas Day (26.12.)',
    'holidayHours.dec27': '27th December',
    'holidayHours.dec28': '28th December',
    'holidayHours.dec29': '29th December',
    'holidayHours.dec30': '30th December',
    'holidayHours.dec31': 'New Year\'s Eve (31.12.)',
    'holidayHours.jan1': 'New Year\'s Day (1.1.)',
    'holidayHours.closed': 'Closed',
    'holidayHours.welcomeMessage': 'Looking forward to your visit during the holidays!',
    'holidayHours.teamSignature': 'Altro Da Tony Team',
    
    // Daily Menu
    'daily.title': 'Weekly Menu',
    'daily.servingTime': 'Served 11:00 - 15:00',
    'daily.disclaimer': 'Menu may change depending on the availability of fresh ingredients',
    'daily.soups': 'Soups',
    'daily.mains': 'Main Courses',
    'daily.desserts': 'Desserts',
    
    // Admin Panel
    'admin.dailyMenu': 'Weekly Menu',
    'admin.mainMenu': 'Main Menu Management',
    'admin.reservations': 'Reservations',
    'admin.monday': 'Monday',
    'admin.tuesday': 'Tuesday',
    'admin.wednesday': 'Wednesday',
    'admin.thursday': 'Thursday',
    'admin.friday': 'Friday',
    'admin.saturday': 'Saturday',
    'admin.sunday': 'Sunday',
    'admin.add': 'Add Item',
    'admin.save': 'Save All',
    'admin.delete': 'Delete',
    'admin.edit': 'Edit',
    'admin.cancel': 'Cancel',
    'admin.name': 'Name',
    'admin.description': 'Description',
    'admin.price': 'Price',
    'admin.category': 'Category',
    'admin.image': 'Image URL',
    'admin.reset': 'Load Default Menu',
    'admin.visible': 'visible',
    'admin.hidden': 'hidden',
    'admin.hide': 'Hide from website',
    'admin.show': 'Show on website',
    
    // Menu Items - Antipasti
    'item.bruschetta.name': 'Bruschetta al Pomodoro',
    'item.bruschetta.desc': 'Grilled bread with tomatoes, basil and olive oil',
    'item.carpaccio.name': 'Carpaccio di Manzo',
    'item.carpaccio.desc': 'Thin slices of beef with arugula and parmesan',
    'item.prosciutto_melone.name': 'Prosciutto e Melone',
    'item.prosciutto_melone.desc': 'Parma ham with fresh melon',
    'item.caprese.name': 'Caprese',
    'item.caprese.desc': 'Mozzarella, tomatoes, basil, olive oil',
    'item.burrata.name': 'Burrata con Pomodorini',
    'item.burrata.desc': 'Burrata with cherry tomatoes and basil',
    
    // Menu Items - Primi (Pasta)
    'item.carbonara.name': 'Spaghetti Carbonara',
    'item.carbonara.desc': 'Spaghetti with pancetta, egg and parmesan',
    'item.aglio_olio.name': 'Spaghetti Aglio e Olio',
    'item.aglio_olio.desc': 'Spaghetti with garlic, olive oil and peperoncino',
    'item.arrabbiata.name': 'Penne all\'Arrabbiata',
    'item.arrabbiata.desc': 'Penne with spicy tomato sauce',
    'item.tagliatelle_ragu.name': 'Tagliatelle al Ragù',
    'item.tagliatelle_ragu.desc': 'Homemade tagliatelle with meat sauce',
    'item.risotto_funghi.name': 'Risotto ai Funghi',
    'item.risotto_funghi.desc': 'Creamy risotto with wild mushrooms',
    'item.gnocchi_gorgonzola.name': 'Gnocchi al Gorgonzola',
    'item.gnocchi_gorgonzola.desc': 'Homemade gnocchi with cheese sauce',
    
    // Menu Items - Pizza
    'item.margherita.name': 'Pizza Margherita',
    'item.margherita.desc': 'Tomato sauce, mozzarella, basil',
    'item.quattro_formaggi.name': 'Pizza Quattro Formaggi',
    'item.quattro_formaggi.desc': 'Four types of cheese',
    'item.prosciutto_funghi.name': 'Pizza Prosciutto e Funghi',
    'item.prosciutto_funghi.desc': 'Ham and mushrooms',
    'item.diavola.name': 'Pizza Diavola',
    'item.diavola.desc': 'Spicy salami, peperoncino',
    
    // Menu Items - Secondi
    'item.scaloppine.name': 'Scaloppine al Limone',
    'item.scaloppine.desc': 'Veal slices in lemon sauce',
    'item.pollo_milanese.name': 'Pollo alla Milanese',
    'item.pollo_milanese.desc': 'Fried chicken cutlet',
    'item.ossobuco.name': 'Ossobuco',
    'item.ossobuco.desc': 'Beef shank braised in wine with gremolata',
    'item.branzino.name': 'Branzino al Forno',
    'item.branzino.desc': 'Baked sea bass with herbs',
    
    // Menu Items - Dolci
    'item.tiramisu.name': 'Tiramisù',
    'item.tiramisu.desc': 'Classic Italian dessert with mascarpone and coffee',
    'item.panna_cotta.name': 'Panna Cotta',
    'item.panna_cotta.desc': 'Cream dessert with forest berries',
    'item.cannoli.name': 'Cannoli Siciliani',
    'item.cannoli.desc': 'Traditional Sicilian tubes with ricotta',
    'item.gelato.name': 'Gelato Artigianale',
    'item.gelato.desc': 'Homemade Italian ice cream',
  },
  it: {
    // Header
    'header.menu': 'Menu',
    'header.gallery': 'Galleria',
    'header.call': 'Chiama',
    'header.reserve': 'Prenota un Tavolo',
    'header.trust': 'valutazione su Google (64+ recensioni)',
    'header.experience': '20+ anni di esperienza',
    
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'Chi Siamo',
    'nav.menu': 'Menu',
    'nav.daily': 'Menu Settimanale',
    'nav.reserve': 'Prenotazione',
    'nav.contact': 'Contatto',
    
    // Hero
    'hero.subtitle': 'Autentica Cucina Italiana nel Cuore di Praga',
    'hero.description': 'Pizza Napoletana tradizionale da Morello Forni • Pasta fresca casera • Ospitalità italiana autentica',
    'hero.viewMenu': 'Guarda il Menu',
    'hero.years': '20+ anni di esperienza',
    'hero.fresh': 'Ingredienti freschi ogni giorno',
    'hero.reserve': 'Prenota un Tavolo',
    'hero.call': 'Chiama',
    'hero.urgency': '⚡ Capacità limitata - Prenota il tuo tavolo in anticipo',
    'hero.address': 'Indirizzo',
    'hero.location': 'Korunní 48, Praga 2',
    'hero.hours': 'Orari di Apertura',
    'hero.schedule': 'Lun-Dom: 11:00 - 23:00',
    'hero.chef': 'Proprietario & Chef',
    'hero.chefName': 'Antonín Sahulka',
    
    // Locale for date picker
    'locale': 'it',
    
    // About
    'about.title': 'Scopri il Gusto\ndella Vera Italia',
    'about.p1': "Da Altro Da Tony uniamo l'amore per la cucina italiana con ingredienti di qualità. Il nostro chef ha più di 20 anni di esperienza nella gastronomia italiana.",
    'about.p2': 'Prepariamo ogni piatto con amore e cura, perché crediamo che una buona cucina unisca le persone.',
    'about.stat1': 'Anni di esperienza',
    'about.stat2': 'Ingredienti freschi',
    'about.stat3': 'Ospiti soddisfatti',
    'about.cta': 'Guarda il Menu',
    'about.chefLabel': 'Proprietario & Chef',
    'about.chefYears': '20+ anni di esperienza',
    'about.ownerTitle': 'Storia del Proprietario',
    'about.ownerP1': "Altro Da Tony non è solo un ristorante – è un sogno realizzato. Dopo più di vent'anni di esperienza nei ristoranti italiani, ho deciso di aprire il mio posto dove posso condividere la mia passione per la cucina italiana autentica e la pizza napoletana tradizionale.",
    'about.ownerP2': "Oggi combino le tecniche tradizionali italiane con gli ingredienti locali freschi per creare un'esperienza gastronomica indimenticabile.",
    'about.ownerP3': "A Altro Da Tony, non è solo la cucina – è l'atmosfera, la famiglia e la condivisione della gioia al tavolo. Ogni ospite è come un amico che accogliamo a casa.",
    'about.ownerQuote': 'La cucina non è solo alimentare le persone – è creare ricordi, emozioni e unire le famiglie al tavolo.',
    'about.ownerQuoteShort': 'Cucinare riguarda le emozioni e unire le persone.',
    'contact.days': 'Lunedì - Domenica',
    'reservation.groups': 'Per gruppi di 10+ persone chiamare',
    'reviews.example': 'Miglior ristorante italiano a Vinohrady. Ottima atmosfera e cibo ancora migliore.',
    
    // Gallery
    'gallery.title': 'Le Nostre Specialità',
    'gallery.subtitle': 'Ogni piatto è preparato con attenzione ai dettagli e rispetto per le tradizioni italiane',
    'gallery.carbonara': 'Pasta Carbonara',
    'gallery.pizza': 'Pizza Margherita',
    'gallery.tiramisu': 'Tiramisù',
    'gallery.burrata': 'Burrata Fresca',
    'gallery.wine': 'Vini Italiani',
    'gallery.oven': 'Forno Morello Forni',
    'gallery.cat.pasta': 'Pasta',
    'gallery.cat.pizza': 'Pizza',
    'gallery.cat.dolci': 'Dolci',
    'gallery.cat.antipasti': 'Antipasti',
    'gallery.cat.wine': 'Vino',
    'gallery.cat.restaurant': 'Ristorante',
    'gallery.question': 'Non vedi l\'ora di gustare l\'autentica cucina italiana?',
    'gallery.cta': 'Prenota un Tavolo',
    
    // Gallery Items
    'gallery.item1.title': 'Pizza Napoletana',
    'gallery.item1.category': 'Dal Forno',
    'gallery.item2.title': 'Interno del Ristorante',
    'gallery.item2.category': 'Dietro le Quinte',
    'gallery.item3.title': 'Altro Da Tony',
    'gallery.item3.category': 'Italia Autentica',
    'gallery.item4.title': 'Espresso Italiano',
    'gallery.item4.category': 'Caffè Premium',
    'gallery.item5.title': 'Pasta Perfetta',
    'gallery.item5.category': 'Fresca Ogni Giorno',
    'gallery.item6.title': 'Ingredienti Freschi',
    'gallery.item6.category': 'Qualità Pura',
    
    // Featured Dish
    'featured.badge': '',
    'featured.title': 'Perché la nostra pizza è così buona?',
    'featured.description': 'Ogni pizza che serviamo è il risultato di anni di prove e perfezionamenti. Lasciamo maturare l\'impasto per 48 ore, rendendolo leggero e digeribile. Gli ingredienti non mentono, per questo usiamo solo pomodori San Marzano e mozzarella fresca. Il forno rotante Morello Forni garantisce un risultato sempre perfetto. Nessuna magia, solo onesto artigianato.',
    'featured.fact': 'Curiosità: I pomodori San Marzano che usiamo crescono su terreno vulcanico sotto il Vesuvio. Sono proprio i minerali della lava a conferire loro quel gusto dolce e specifico che non può essere sostituito.',
    'featured.chefChoice': '',
    
    // Menu
    'menu.title': 'Menu',
    'menu.subtitle': 'Ingredienti freschi, ricette tradizionali e amore per la cucina italiana',
    'menu.daily': 'Menu Settimanale',
    'menu.antipasti': 'Antipasti',
    'menu.insalate': 'Insalate',
    'menu.pasta': 'Pasta',
    'menu.pizza': 'Pizza',
    'menu.secondi': 'Primi',
    'menu.dolci': 'Dolci',
    'menu.primi': 'Primi Piatti',
    'menu.badge.popular': 'Più Popolare',
    'menu.badge.chef': 'Raccomandazione dello Chef',
    'menu.badge.vegetarian': 'Vegetariano',
    'menu.allergens': 'Hai allergie o restrizioni dietetiche?',
    'menu.allergensText': 'Non esitare a chiedere al nostro personale. Saremo felici di personalizzare il menu per te.',
    'menu.cta': 'Prenota un Tavolo',
    
    // Menu Categories - Drinks
    'menu.drinks': 'Bibite',
    'menu.wines': 'Vini',
    'menu.wines_white': 'Vini Bianchi',
    'menu.wines_red': 'Vini Rossi',
    'menu.wines_rose': 'Vini Rosati',
    'menu.wines_sparkling': 'Prosecco & Vini Spumanti',
    'menu.beers': 'Birre',
    'menu.aperitivi': 'Aperitivi',
    'menu.cocktails': 'Cocktail',
    'menu.digestivi': 'Digestivi',
    'menu.grappa': 'Grappa',
    'menu.nonalcoholic': 'Bibite Non Alcoliche',
    'menu.coffee': 'Caffè',
    'menu.food': 'Cibo',
    
    // Wine descriptions
    'menu.wine.bottle': 'bottiglia',
    'menu.wine.glass': 'bicchiere',
    
    // Reviews
    'reviews.title': 'Cosa Dicono i Nostri Ospiti',
    'reviews.based': 'Basato su',
    'reviews.reviews': '+ recensioni',
    'reviews.google': 'Google Reviews',
    'reviews.all': 'Visualizza tutte le recensioni su Google',
    'reviews.write': 'Scrivi una recensione',
    'reviews.join': 'Unisciti ai nostri ospiti soddisfatti',
    'reviews.joinText': "Prenota un tavolo e vivi l'autentica ospitalità italiana",
    'reviews.cta': 'Prenota un Tavolo',
    
    // Reservation
    'reservation.title': 'Prenota un Tavolo',
    'reservation.subtitle': 'Riserva il tuo posto nel nostro ristorante e goditi l\'autentica cucina italiana',
    'reservation.urgency': 'Capacità limitata - Prenota in anticipo!',
    'reservation.name': 'Nome Completo',
    'reservation.email': 'Email',
    'reservation.phone': 'Telefono',
    'reservation.guests': 'Numero di Ospiti',
    'reservation.date': 'Data',
    'reservation.datePlaceholder': 'Seleziona data',
    'reservation.time': 'Ora',
    'reservation.timePlaceholder': 'Seleziona ora',
    'reservation.message': 'Messaggio',
    'reservation.messagePlaceholder': 'Richieste speciali, allergie, celebrazione...',
    'reservation.occasion': 'Occasione Speciale?',
    'reservation.occasionPlaceholder': 'Seleziona occasione',
    'reservation.occasionBusiness': 'Lavoro',
    'reservation.occasionRomance': 'Romantico',
    'reservation.occasionFriends': 'Amici',
    'reservation.occasionFamily': 'Famiglia',
    'reservation.occasionCelebration': 'Celebrazione',
    'reservation.occasionOther': 'Altro',
    'reservation.submit': 'Conferma Prenotazione',
    'reservation.trust1': 'Conferma entro 1 ora',
    'reservation.trust2': 'Nessuna commissione',
    'reservation.trust3': 'Facile modificare la prenotazione',
    'reservation.alternative': 'Preferisci il contatto personale?',
    'reservation.open': 'Aperto Lun-Dom: 11:00 - 23:00',
    'reservation.success': 'Grazie per la prenotazione! La tua prenotazione è stata inviata per l\'elaborazione.',
    'reservation.person': 'persona',
    'reservation.persons2': 'persone',
    'reservation.persons5': 'persone',
    'reservation.sending': 'Invio in corso...',
    'reservation.summary': 'Riepilogo prenotazione',
    'reservation.continue': 'Continua',
    'reservation.back': 'Indietro',
    'reservation.fillAll': 'è un campo obbligatorio',
    'reservation.error': 'Qualcosa è andato storto. Prova di nuovo o contattaci per telefono.',
    
    // Contact
    'contact.title': 'Contatto',
    'contact.address': 'Indirizzo',
    'contact.addressLine1': 'Korunní 48',
    'contact.addressLine2': '120 00 Praga 2 - Vinohrady',
    'contact.phone': 'Telefono',
    'contact.email': 'Email',
    'contact.hours': 'Orari di Apertura',
    'contact.schedule': 'Lunedì - Domenica: 11:00 - 23:00',
    
    // Footer
    'footer.about': 'Autentica cucina italiana nel cuore di Praga. Un business di famiglia con tradizione e amore per la gastronomia italiana.',
    'footer.menu': 'Menu',
    'footer.contact': 'Contatto',
    'footer.hours': 'Orari di Apertura:',
    'footer.schedule': 'Lun-Dom: 11:00 - 23:00',
    'footer.kitchenUntil': 'La cucina cuoce fino alle 22:00',
    'footer.copyright': 'Altro da Tony. Tutti i diritti riservati.',
    'footer.made': 'Fatto con',
    'footer.madeFor': 'per gli amanti della cucina italiana',
    
    // Holiday Hours
    'holidayHours.title': 'Orari di Apertura Durante le Feste',
    'holidayHours.subtitle': 'Vi auguriamo una bella festa e ci aspettiamo il vostro arrivo',
    'holidayHours.dec24': 'Vigilia di Natale (24.12.)',
    'holidayHours.dec25': '1° Giorno di Natale (25.12.)',
    'holidayHours.dec26': '2° Giorno di Natale (26.12.)',
    'holidayHours.dec27': '27 Dicembre',
    'holidayHours.dec28': '28 Dicembre',
    'holidayHours.dec29': '29 Dicembre',
    'holidayHours.dec30': '30 Dicembre',
    'holidayHours.dec31': 'Capodanno (31.12.)',
    'holidayHours.jan1': '1° Gennaio (1.1.)',
    'holidayHours.closed': 'Chiuso',
    'holidayHours.welcomeMessage': 'Ci aspettiamo il vostro arrivo durante le feste!',
    'holidayHours.teamSignature': 'Team Altro Da Tony',
    
    // Daily Menu
    'daily.title': 'Menu Settimanale',
    'daily.servingTime': 'Servito 11:00 - 15:00',
    'daily.disclaimer': 'Il menu può variare a seconda della disponibilità di ingredienti freschi',
    'daily.soup': 'Zuppa',
    'daily.starter': 'Antipasto',
    'daily.main': 'Primo',
    'daily.dessert': 'Dolce',
    'daily.soups': 'Zuppe',
    'daily.mains': 'Primi',
    'daily.desserts': 'Dolci',
    
    // Admin Panel
    'admin.dailyMenu': 'Menu Settimanale',
    'admin.mainMenu': 'Gestione Menu Principale',
    'admin.reservations': 'Prenotazioni',
    'admin.monday': 'Lunedì',
    'admin.tuesday': 'Martedì',
    'admin.wednesday': 'Mercoledì',
    'admin.thursday': 'Giovedì',
    'admin.friday': 'Venerdì',
    'admin.saturday': 'Sabato',
    'admin.sunday': 'Domenica',
    'admin.add': 'Aggiungi Elemento',
    'admin.save': 'Salva Tutto',
    'admin.delete': 'Elimina',
    'admin.edit': 'Modifica',
    'admin.cancel': 'Annulla',
    'admin.name': 'Nome',
    'admin.description': 'Descrizione',
    'admin.price': 'Prezzo',
    'admin.category': 'Categoria',
    'admin.image': 'URL Immagine',
    'admin.reset': 'Carica Menu Predefinito',
    'admin.visible': 'visibili',
    'admin.hidden': 'nascosti',
    'admin.hide': 'Nascondi dal Sito Web',
    'admin.show': 'Mostra sul Sito Web',
    
    // Menu Items - Antipasti
    'item.bruschetta.name': 'Bruschetta al Pomodoro',
    'item.bruschetta.desc': 'Grilovaný chléb s rajčaty, bazalkou a olivovým olejem',
    'item.carpaccio.name': 'Carpaccio di Manzo',
    'item.carpaccio.desc': 'Tenké plátky hovězího masa s rukolou a parmazánem',
    'item.prosciutto_melone.name': 'Prosciutto e Melone',
    'item.prosciutto_melone.desc': 'Parmská šunka s čerstvým melounem',
    'item.caprese.name': 'Caprese',
    'item.caprese.desc': 'Mozzarella, rajčata, bazalka, olivový olej',
    'item.burrata.name': 'Burrata con Pomodorini',
    'item.burrata.desc': 'Burrata s cherry rajčátky a bazalkou',
    
    // Menu Items - Primi (Pasta)
    'item.carbonara.name': 'Spaghetti Carbonara',
    'item.carbonara.desc': 'Spaghetti s pancettou, vejcem a parmazánem',
    'item.aglio_olio.name': 'Spaghetti Aglio e Olio',
    'item.aglio_olio.desc': 'Spaghetti s česnekem, olivovým olejem a peperoncinem',
    'item.arrabbiata.name': 'Penne all\'Arrabbiata',
    'item.arrabbiata.desc': 'Penne s pikantní rajčatovou omáčkou',
    'item.tagliatelle_ragu.name': 'Tagliatelle al Ragù',
    'item.tagliatelle_ragu.desc': 'Domácí tagliatelle s masovou omáčkou',
    'item.risotto_funghi.name': 'Risotto ai Funghi',
    'item.risotto_funghi.desc': 'Krémové rizoto s lesními houbami',
    'item.gnocchi_gorgonzola.name': 'Gnocchi al Gorgonzola',
    'item.gnocchi_gorgonzola.desc': 'Domácí gnocchi se sýrovou omáčkou',
    
    // Menu Items - Pizza
    'item.margherita.name': 'Pizza Margherita',
    'item.margherita.desc': 'Rajčatová omáčka, mozzarella, bazalka',
    'item.quattro_formaggi.name': 'Pizza Quattro Formaggi',
    'item.quattro_formaggi.desc': 'Čtyři druhy sýrů',
    'item.prosciutto_funghi.name': 'Pizza Prosciutto e Funghi',
    'item.prosciutto_funghi.desc': 'Šunka a žampiony',
    'item.diavola.name': 'Pizza Diavola',
    'item.diavola.desc': 'Pikantní salám, peperoncino',
    
    // Menu Items - Secondi
    'item.scaloppine.name': 'Scaloppine al Limone',
    'item.scaloppine.desc': 'Telecí plátky v citronové omáčce',
    'item.pollo_milanese.name': 'Pollo alla Milanese',
    'item.pollo_milanese.desc': 'Smažený kuřecí řízek',
    'item.ossobuco.name': 'Ossobuco',
    'item.ossobuco.desc': 'Hovězí koleno na víně s gremolata',
    'item.branzino.name': 'Branzino al Forno',
    'item.branzino.desc': 'Pečený mořský vlk s bylinkami',
    
    // Menu Items - Dolci
    'item.tiramisu.name': 'Tiramisù',
    'item.tiramisu.desc': 'Klasický italský dezert s mascarpone a kávou',
    'item.panna_cotta.name': 'Panna Cotta',
    'item.panna_cotta.desc': 'Smetanový dezert s lesním ovocem',
    'item.cannoli.name': 'Cannoli Siciliani',
    'item.cannoli.desc': 'Tradiční sicilské trubičky s ricottou',
    'item.gelato.name': 'Gelato Artigianale',
    'item.gelato.desc': 'Domácí italská zmrzlina',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('cs');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['cs']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}